name: 'Bass Rock Framing & Gallery'
favicon: null
layout_spectrum: 0.9144
typography_spectrum: 0.73842
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#202126'
    - '#8c8990'
    - '#64605f'
    - '#dfc9c7'
  brandStrength: 0.9375
  lightness: 0.5257173448335379
  saturation: 0.625
  rhythmicContrast: 0.5829362308140844
purpose: []
