name: 'Bass Rock Framing & Gallery'
favicon: null
layout_spectrum: 0.9144
typography_spectrum: 0.5902655902318656
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.8318503040354699
  lightness: 0.5257173448335379
  saturation: 0.5501253965776414
  rhythmicContrast: 0.5829362308140844
purpose: []
